title: Paul's Bikes
email: pauboutin@gmail.com
description: >
  Custom motorcycles by Paul
baseurl: "/bikes"
url: "https://paulboutin.github.io"
instagram_username: pauboutin
show_downloads: false
show_title: false
google_analytics: G-1DS9QJX73E
logo: /assets/img/logo2.svg
collections:
  builds:
    output: true
    permalink: /:collection/:name
    output_ext: false

remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
- jekyll-last-modified-at

# The default date format, used if none is specified in the tag.
last-modified-at:
    date-format: '%m.%d.%y'