title: Paul's Bike Builds
email: pauboutin@gmail.com
description: >
  Motorcycle builds by Paul
baseurl: "/bikes"
url: "https://paulboutin.github.io"
instagram_username: pauboutin
show_downloads: false
google_analytics: G-1DS9QJX73E

remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme